version: "3.8"

services:
  carla:
    image: carlasim/carla:0.9.15
    platform: linux/amd64
    ports:
      - "2000-2002:2000-2002"
    command: ./CarlaUE4.sh -RenderOffScreen

  rosbridge:
    build:
      context: ./ros-bridge
    depends_on:
      - carla
    environment:
      - ROS_DOMAIN_ID=0
    command: ros2 launch carla_ros_bridge carla_ros_bridge.launch.py

  code:
    build:
      context: ./code
    depends_on:
      - rosbridge
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - ./code:/workspace
    command: python3 main.py
